#
# Installs Spotify
#
- name: Checking for 'spotify' installation
  command: dpkg-query -W spotify-client
  register: result
  failed_when: result.rc > 1
  changed_when: result.rc == 1
  tags:
    - packages
    - packages.apps
    - spotify
    
- name: Adding apt keys for 'spotify'
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80 
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  when: result.rc == 1
  tags:
    - packages
    - packages.apps
    - spotify
    
- name: Adding 'spotify' repository
  apt_repository: 
    repo: 'deb http://repository.spotify.com stable non-free'
  when: result.rc == 1
  tags:
    - packages
    - packages.apps
    - spotify

- name: Installing 'spotify' package
  apt: 
    name: spotify-client 
    update_cache: yes
  when: result.rc == 1
  tags:
    - packages
    - packages.apps
    - spotify
